#!/usr/bin/env python3
##
## EPITECH PROJECT, 2022
## exercises.py
## File description:
## exercises
##

def main():
    i = 1
    while i <= 100:
        testthree = i % 3
        testfive = i % 5
        if testthree == 0 and testfive != 0:
            print("Three")
        elif testthree != 0 and testfive == 0:
            print("Five")
        elif testthree == 0 and testfive == 0:
            print("ThreeFive")
        else :
            print(i)
        i += 1
    return

if __name__ == "__main__":
    main()